### ISSUE TITLE
build error with v3.6.14 when compiling with GCC 7.5.0

### ISSUE THREAD

**Issue by pedrolcl** [EmbeddedSynth/sonivox-fork#30]
```
[ 96%] Building C object CMakeFiles/sonivox-objects.dir/arm-wt-22k/lib_src/wt_200k_G.c.o
gcc-mp-7 -DDLS_SYNTHESIZER -DEAS_WT_SYNTH -DMAX_SYNTH_VOICES=64 -DNUM_OUTPUT_CHANNELS=2 -DUNIFIED_DEBUG_MESSAGES -D_16_BIT_SAMPLES -D_CHORUS_ENABLED -D_FILTER_ENABLED -D_REVERB_ENABLED -D_SAMPLE_RATE_44100 -I/src/sonivox-3.6.14/build/libsonivox -I/src/sonivox-3.6.14/arm-wt-22k/host_src -I/src/sonivox-3.6.14/arm-wt-22k/lib_src -I/src/sonivox-3.6.14/fakes -O2 -fPIC -Wno-unused-parameter -Wno-unused-value -Wno-unused-variable -Wno-unused-function -Wno-misleading-indentation -Wno-attributes -o CMakeFiles/sonivox-objects.dir/arm-wt-22k/lib_src/wt_200k_G.c.o -c /src/sonivox-3.6.14/arm-wt-22k/lib_src/wt_200k_G.c
/src/sonivox-3.6.14/arm-wt-22k/lib_src/wt_200k_G.c:114:5: error: initializer element is not constant
     0x00200000 | sampleRate,
     ^~~~~~~~~~
/src/sonivox-3.6.14/arm-wt-22k/lib_src/wt_200k_G.c:114:5: note: (near initialization for 'easSoundLib.libAttr')
```

This problem appears to have been introduced by PR https://github.com/pedrolcl/sonivox/pull/20; GCC didn't allow doing this before GCC 8.1, per https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69960#c18. (Clang allowed this syntax for a longer time.)
