### PR TITLE
Fix wt_200k_G.c "initializer element is not constant" error with GCC < 8.1

### LINKED ISSUE #30: build error with v3.6.14 when compiling with GCC 7.5.0
```
[ 96%] Building C object CMakeFiles/sonivox-objects.dir/arm-wt-22k/lib_src/wt_200k_G.c.o
gcc-mp-7 -DDLS_SYNTHESIZER -DEAS_WT_SYNTH -DMAX_SYNTH_VOICES=64 -DNUM_OUTPUT_CHANNELS=2 -DUNIFIED_DEBUG_MESSAGES -D_16_BIT_SAMPLES -D_CHORUS_ENABLED -D_FILTER_ENABLED -D_REVERB_ENABLED -D_SAMPLE_RATE_44100 -I/src/sonivox-3.6.14/build/libsonivox -I/src/sonivox-3.6.14/arm-wt-22k/host_src -I/src/sonivox-3.6.14/arm-wt-22k/lib_src -I/src/sonivox-3.6.14/fakes -O2 -fPIC -Wno-unused-parameter -Wno-unused-value -Wno-unused-variable -Wno-unused-function -Wno-misleading-indentation -Wno-attributes -o CMakeFiles/sonivox-objects.dir/arm-wt-22k/lib_src/wt_200k_G.c.o -c /src/sonivox-3.6.14/arm-wt-22k/lib_src/wt_200k_G.c
/src/sonivox-3.6.14/arm-wt-22k/lib_src/wt_200k_G.c:114:5: error: initializer element is not constant
     0x00200000 | sampleRate,
     ^~~~~~~~~~
/src/sonivox-3.6.14/arm-wt-22k/lib_src/wt_200k_G.c:114:5: note: (near initialization for 'easSoundLib.libAttr')
```

This problem appears to have been introduced by PR https://github.com/pedrolcl/sonivox/pull/20; GCC didn't allow doing this before GCC 8.1, per https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69960#c18. (Clang allowed this syntax for a longer time.)

### PR DESCRIPTION
**Pull request by dwatteau**
Hello,

We use Sonivox as part of ScummVM, and I've hit the following build error with v3.6.14 when compiling with GCC 7.5.0:

```
[ 96%] Building C object CMakeFiles/sonivox-objects.dir/arm-wt-22k/lib_src/wt_200k_G.c.o
gcc-mp-7 -DDLS_SYNTHESIZER -DEAS_WT_SYNTH -DMAX_SYNTH_VOICES=64 -DNUM_OUTPUT_CHANNELS=2 -DUNIFIED_DEBUG_MESSAGES -D_16_BIT_SAMPLES -D_CHORUS_ENABLED -D_FILTER_ENABLED -D_REVERB_ENABLED -D_SAMPLE_RATE_44100 -I/src/sonivox-3.6.14/build/libsonivox -I/src/sonivox-3.6.14/arm-wt-22k/host_src -I/src/sonivox-3.6.14/arm-wt-22k/lib_src -I/src/sonivox-3.6.14/fakes -O2 -fPIC -Wno-unused-parameter -Wno-unused-value -Wno-unused-variable -Wno-unused-function -Wno-misleading-indentation -Wno-attributes -o CMakeFiles/sonivox-objects.dir/arm-wt-22k/lib_src/wt_200k_G.c.o -c /src/sonivox-3.6.14/arm-wt-22k/lib_src/wt_200k_G.c
/src/sonivox-3.6.14/arm-wt-22k/lib_src/wt_200k_G.c:114:5: error: initializer element is not constant
     0x00200000 | sampleRate,
     ^~~~~~~~~~
/src/sonivox-3.6.14/arm-wt-22k/lib_src/wt_200k_G.c:114:5: note: (near initialization for 'easSoundLib.libAttr')
```

See [this example on Godbolt](https://godbolt.org/z/68sdozsqz) for a minimal test with this environment.

This problem appears to have been introduced by PR #20; GCC didn't allow doing this before GCC 8.1, per https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69960#c18. (Clang allowed this syntax for a longer time.)

Using an `enum` instead of a `const EAS_U32` variable is enough to let it build with older GCC releases.

### CODE REVIEW

**Comment by pedrolcl** [comment]
We do not allow merge requests into master directly

**Review by pedrolcl — CHANGES_REQUESTED** [review]
> Using an enum instead of a const EAS_U32 variable is enough to let it build with older GCC releases.

In my opinion, a better fix should be something like this:

```C
#ifdef _SAMPLE_RATE_44100
#define SAMPLE_RATE 0xAC44
#else
#define SAMPLE_RATE 0x5622;
#endif
```

https://godbolt.org/z/Pjn3da7Gv

using enum for declaring a constant may be legal, but I don't like the taste.

**Comment by dwatteau** [comment]
> We do not allow merge requests into master directly

OK. To make it easier for contributors to know your workflow, I would suggest adding some [GitHub contribution guidelines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) and/or adding a [Pull Request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) to your repository, then.

> using enum for declaring a constant may be legal, but I don't like the taste.

Sure. I've adjusted the PR for this.

**Review by pedrolcl — APPROVED** [review]
